AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  loncel-api-connector

  Sample SAM Template for loncel-api-connector

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10
    MemorySize: 128

    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
Resources:
  LoncelApiConnectorFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: loncel-api-con/
      Handler: app.lambda_handler
      Runtime: python3.11
      FunctionUrlConfig:
        AuthType: NONE
      Architectures:
        - x86_64
      Environment:
        Variables:
          LONCEL_API_KEY: "35uwzReU338TUnLnrOtUet3s67i1GK91tk2noIw7"
          LONCEL_API_USER: "daniel@rfe.co.nz"
          LONCEL_API_PWD: "sigma1987E$"
          KEY: "FXofN7iqGbBQ4Ej0nLKHW3CY6u8t4"

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  LoncelApiConnectorFunction:
    Description: HTTP endpoint URL for loncel api connector function
    Value: !Sub "https://${LoncelApiConnectorFunction}.execute-api.${AWS::Region}.amazonaws.com/Prod/loncel-api-connector/"
  LoncelApiConnectorFunctionArn:
    Description: Loncel Api Connector Lambda Function ARN
    Value: !GetAtt LoncelApiConnectorFunction.Arn
